import { ArrowUpRight, BookOpen, HeartHandshake, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { Shell } from "@/components/AcademyShell";

const principles = [
  { index: "01", title: "Structure before noise", copy: "The internet already contains remarkable technical material. Our job is to place the right piece in front of you at the right moment, with enough context to make it usable." },
  { index: "02", title: "Sources stay visible", copy: "We point back to the original lecture, paper, lab, or course page. Rampage is a guide and a workspace, not a replacement for the people who created the material." },
  { index: "03", title: "Progress should feel earned", copy: "Small completions, honest checkpoints, and difficult assessments make a learning record more meaningful than a wall of empty promises." },
  { index: "04", title: "Access is part of the design", copy: "BlackVault Foundation is built around the belief that serious technical education should be easier to navigate and more affordable to reach." },
];

export default function About() {
  return <Shell><main className="about-page">
    <section className="about-hero"><div><p className="eyebrow"><span className="lime-dot" /> BLACKVAULT FOUNDATION / ABOUT</p><h1>A clearer way<br /><em>into hard things.</em></h1><p className="about-lede">BlackVault Foundation is building Rampage as a structured way to learn systems, infrastructure, and the ideas beneath modern software. The work is practical: find the best public material, give it shape, and help a learner take the next step.</p><div className="hero-actions"><Link className="primary-cta" href="/paths">Explore the learning paths <ArrowUpRight size={18} /></Link><Link className="text-cta" href="/#sources">View the source layer <ArrowUpRight size={16} /></Link></div></div><div className="about-stamp"><span>EST.</span><strong>BV<br />/ R</strong><small>STRUCTURE<br />ACCESS<br />DISCIPLINE</small></div></section>
    <section className="about-founder"><div className="section-index">01 <span>/</span> THE FOUNDER</div><div className="about-founder-grid"><div><h2>Built by a learner<br /><i>who kept looking closer.</i></h2><p>Adarsh Kushwah is an AI Engineer and Developer and the founder of BlackVault Rampage. His work on the academy comes from a simple frustration: important technical knowledge is everywhere, but the path through it is often not.</p><p>Founder-provided credential note: Adarsh is certified by Oracle and the Government of India. These details are presented as provided by the founder; Rampage does not issue or replace those credentials.</p></div><div className="about-founder-card"><Sparkles size={20} /><strong>ADARSH<br />KUSHWAH</strong><span>AI ENGINEER / DEVELOPER</span><div className="about-rule" /><small>FOUNDER / BLACKVAULT FOUNDATION</small></div></div></section>
    <section className="about-mission"><div className="section-index">02 <span>/</span> THE MISSION</div><div className="about-mission-grid"><div><h2>Provide a structural<br /><i>way to learn.</i></h2></div><div><p>That means fewer vague roadmaps and more deliberate sequences. A course should tell you what to open, what to notice, what to build, and what to do when the first explanation does not land.</p><p>Rampage brings together courses, source documents, labs, reading rooms, progress tracking, and assessment into one place. It is designed for the long middle of learning — after the excitement of starting and before the confidence of knowing.</p></div></div></section>
    <section className="about-principles"><div className="section-index">03 <span>/</span> HOW WE WORK</div><div className="principle-grid">{principles.map((principle) => <article key={principle.index}><span>{principle.index}</span><h3>{principle.title}</h3><p>{principle.copy}</p></article>)}</div></section>
    <section className="about-foundation"><div className="foundation-mark"><HeartHandshake size={24} /><span>BLACKVAULT<br />FOUNDATION</span></div><div><div className="section-index">04 <span>/</span> THE FOUNDATION</div><h2>Make serious learning<br /><i>more affordable.</i></h2><p>BlackVault Foundation is the part of the project that keeps the mission bigger than a product interface. We want the best public technical material to be easier to reach, easier to understand, and easier to return to when life interrupts the plan.</p><div className="about-values"><span><BookOpen size={16} /> OPEN SOURCES</span><span><ShieldCheck size={16} /> HONEST PROGRESS</span><span><HeartHandshake size={16} /> ACCESS FIRST</span></div></div></section>
    <section className="about-close"><p>Rampage is still being built. That is intentional. The library will grow, the paths will get sharper, and the standard for what earns a place here will stay high.</p><Link className="primary-cta" href="/">Return to the academy <ArrowUpRight size={18} /></Link></section>
  </main></Shell>;
}
