import { BadgeCheck, CheckCircle2, ExternalLink, Search, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { Shell } from "@/components/AcademyShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { courses } from "@/data/catalog";

export default function CertificateVerify() {
  const [, params] = useRoute("/certificate/verify/:recordId");
  const recordId = params?.recordId?.toUpperCase() ?? "";
  const input = recordId;
  const result = trpc.certificate.verify.useQuery({ recordId }, { enabled: /^RMPV-\d{4}-[A-F0-9]{20}$/i.test(recordId), retry: false });
  const course = result.data ? courses.find(item => item.id === result.data.courseId) : undefined;

  return <Shell><main className="verification-page"><div className="verification-wrap"><div className="verification-kicker"><ShieldCheck size={16} /> RAMPAGE / PUBLIC RECORD CHECK</div><div className="verification-hero"><div><p className="eyebrow"><span className="signal-dot" /> CERTIFICATE VERIFICATION</p><h1>Proof you can <em>inspect.</em></h1><p>Enter the privacy-safe record ID printed on a BlackVault Rampage certificate. This page checks the issued record without exposing an email address, account ID, or completion hash.</p></div><div className="verification-seal"><BadgeCheck size={28} /><span>SERVER<br />CHECKED</span></div></div><form className="verification-search" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form).get("recordId"); if (typeof value === "string" && value.trim()) window.location.href = `/certificate/verify/${encodeURIComponent(value.trim())}`; }}><label htmlFor="certificate-record-id">Public record ID</label><div><Input id="certificate-record-id" name="recordId" defaultValue={input} placeholder="RMPV-2026-…" autoCapitalize="characters" /><Button type="submit"><Search size={16} /> Verify record</Button></div></form>{result.isLoading && <div className="verification-state"><span className="signal-dot" /> Checking the issued record…</div>}{result.isError && <div className="verification-state verification-state--error" role="alert"><strong>Record not found.</strong><span>Check the ID and try again. Public records are intentionally non-guessable.</span></div>}{result.data && <section className="verification-card" aria-live="polite"><div className="verification-card-top"><span className="verification-status"><CheckCircle2 size={16} /> ISSUED / VERIFIED</span><span>{new Date(result.data.issuedAt).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })}</span></div><h2>{result.data.learnerName}</h2><p className="verification-course">{course?.title ?? result.data.courseId}</p><dl><div><dt>Record ID</dt><dd>{result.data.publicRecordId}</dd></div><div><dt>Certificate</dt><dd>{result.data.certificateId}</dd></div><div><dt>Evidence</dt><dd>{result.data.lessonCount ? `${result.data.lessonCount} lessons completed` : "Completion record sealed"}</dd></div></dl><p className="verification-note">This is a digital learning certificate issued by BlackVault Rampage. It is not an academic degree, professional license, or government accreditation.</p><Link href={`/certificate/${result.data.courseId}`}><ExternalLink size={15} /> Open certificate surface</Link></section>}{!recordId && <div className="verification-state verification-state--quiet">Use the ID from a Rampage certificate to begin a public check.</div>}<div className="verification-footer"><Link href="/">Return to Rampage</Link><span>Privacy-safe by design.</span></div></div></main></Shell>;
}
