// Guided paths: beginner-friendly route cards with one next action and clear progression context.
import { ArrowRight, BookOpen, Check, Clock3, Compass, Layers3 } from "lucide-react";
import { Link, useRoute } from "wouter";
import { findPath, learningPaths, pathItem } from "@/data/paths";
import { Shell } from "@/components/AcademyShell";
import { useProgress } from "@/hooks/useProgress";

export default function Paths() { const [, params] = useRoute("/paths/:pathId"); const selected = params?.pathId ? findPath(params.pathId) : undefined; return <Shell><main className="paths-page">{selected ? <PathDetail path={selected} /> : <><section className="paths-hero"><p className="eyebrow"><span className="lime-dot" /> RAMPAGE / GUIDED PATHS</p><h1>One good<br /><em>next step.</em></h1><p>Rampage is not a shelf of links. Choose a path, start at the right level, and let each course or source hand you the next move.</p></section><section className="path-grid-section"><div className="section-index">01 <span>/</span> CHOOSE YOUR ROUTE</div><div className="path-grid">{learningPaths.map((path, index) => <Link key={path.id} href={`/paths/${path.id}`} className="path-card"><div className="path-card-top"><span>{String(index + 1).padStart(2, "0")}</span><span>{path.level}</span></div><h2>{path.title}</h2><p>{path.subtitle}</p><div className="path-card-foot"><span><Clock3 size={13} /> {path.time}</span><ArrowRight size={17} /></div></Link>)}</div></section></>}</main></Shell>; }
function PathDetail({ path }: { path: ReturnType<typeof findPath> & {} }) { const { done } = useProgress(); return <section className="path-detail"><div className="path-detail-head"><div><Link className="back-link" href="/paths"><Compass size={14} /> All paths</Link><p className="eyebrow"><span className="lime-dot" /> PATH / {path.level}</p><h2>{path.title}<br /><i>{path.subtitle}</i></h2><p>{path.promise}</p></div><div className="path-signal"><strong>{path.steps.length}</strong><span>STEPS<br />TO START</span></div></div><div className="path-steps">{path.steps.map((step, index) => { const item = pathItem(step.id, step.type) as any; const href = step.type === "course" ? `/course/${step.id}` : `/resources/read/${step.id}`; const courseDone = step.type === "course" && item?.phases?.flatMap((phase: any) => phase.lessons).filter((lesson: any) => done.includes(`${item.id}:${lesson.id}`)).length; return <div className="path-step" key={step.id}><div className="path-step-num">{String(index + 1).padStart(2, "0")}</div><div className="path-step-line" /><div className="path-step-body"><span className="path-step-type">{step.type === "course" ? <Layers3 size={13} /> : <BookOpen size={13} />} {step.type}</span><h3>{step.label}</h3><p>{step.why}</p>{courseDone ? <small><Check size={12} /> {courseDone} lessons complete</small> : null}</div><Link className="path-step-cta" href={href}>Open <ArrowRight size={15} /></Link></div>})}</div></section>; }
