// PDF reading room: embeds canonical sources when supported and always preserves an original-source fallback.
import { ArrowLeft, ArrowUpRight, BookOpen, Check, Download, ExternalLink, FileText } from "lucide-react";
import { Link, useRoute } from "wouter";
import { findPdf } from "@/data/catalog";
import { Shell } from "@/components/AcademyShell";
import { useEffect, useState } from "react";

export default function ResourceReader() {
  const [, params] = useRoute("/resources/read/:resourceId");
  const item = findPdf(params?.resourceId || "");
  const [read, setRead] = useState(() => item ? localStorage.getItem(`rampage-read-${item.id}`) === "1" : false);
  useEffect(() => { if (item && read) localStorage.setItem(`rampage-read-${item.id}`, "1"); }, [item, read]);
  if (!item) return <Shell><main className="reader-page"><div className="reader-not-found"><FileText size={30} /><h1>Source not found.</h1><Link href="/resources">Return to the reading room <ArrowUpRight size={15} /></Link></div></main></Shell>;
  return <Shell><main className="reader-page"><div className="reader-breadcrumb"><Link href="/resources"><ArrowLeft size={14} /> Reading room</Link><span>/</span><span>{item.topic}</span><span>/</span><b>{item.title}</b></div><section className="reader-layout"><div className="reader-main"><div className="reader-heading"><p className="eyebrow"><span className="lime-dot" /> OPEN SOURCE / READING ROOM</p><h1>{item.title}</h1><p>{item.note}</p></div><div className="pdf-reader-frame"><iframe title={`PDF reader for ${item.title}`} src={item.url.includes(".pdf") ? item.url : `${item.url}#page=1`} /><div className="reader-fallback"><FileText size={18} /> If the source does not embed, <a href={item.url} target="_blank" rel="noreferrer">open the original</a>.</div></div><div className="reader-actions"><button className={read ? "reader-complete completed" : "reader-complete"} onClick={() => setRead(!read)}>{read ? <Check size={16} /> : <BookOpen size={16} />} {read ? "Marked read" : "Mark as read"}</button><a href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Open original source</a><a href={item.url} target="_blank" rel="noreferrer"><Download size={15} /> Source download</a></div></div><aside className="reader-aside"><div className="reader-fact"><span className="aside-label"><FileText size={14} /> DOCUMENT CARD</span><h2>{item.topic}</h2><dl><div><dt>AUTHOR</dt><dd>{item.author}</dd></div><div><dt>INSTITUTION</dt><dd>{item.institution}</dd></div><div><dt>LEVEL</dt><dd>{item.level}</dd></div><div><dt>EST. READ</dt><dd>{item.readTime}</dd></div></dl></div><div className="reader-fact"><span className="aside-label"><ArrowUpRight size={14} /> CONTINUE PATH</span><p>Use this source as a companion to the related course. Read for the concept, then return to the lab for the evidence.</p><Link className="reader-course-link" href={`/course/${item.relatedCourse}`}>Open related course <ArrowUpRight size={14} /></Link></div><div className="reader-fact"><span className="aside-label">TAGS</span><div className="reader-tags">{item.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div></div></aside></section></main></Shell>;
}
