import { ArrowUpRight, BookOpen, ExternalLink, FileText, Filter, Github, Link2, MonitorUp, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { pdfCatalog, resourceCatalog, type Resource } from "@/data/catalog";
import { canStudyInline, classifyInlineSource, sourceHost } from "@/data/learningSources";
import { Shell } from "@/components/AcademyShell";

function ResourceBadge({ resource }: { resource: Resource }) {
  const kind = classifyInlineSource(resource.url);
  return <span className={`resource-inline-badge resource-inline-badge--${kind}`}>{kind === "pdf" ? "PDF" : kind === "web" ? "INLINE" : kind === "repository" ? "REPO" : kind === "video" ? "VIDEO" : "LINK"}</span>;
}

export default function Resources() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("ALL");
  const [selectedSource, setSelectedSource] = useState<Resource>(() => resourceCatalog.find((resource) => canStudyInline(resource.url)) || resourceCatalog[0]);
  const filters = ["ALL", "Operating Systems", "Distributed Systems", "Networking", "Compilers & Architecture", "Developer Tools"];
  const visible = useMemo(() => pdfCatalog.filter((item) => (filter === "ALL" || item.topic === filter) && `${item.title} ${item.author} ${item.institution} ${item.topic} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  const sourceKind = classifyInlineSource(selectedSource.url);
  const canEmbed = canStudyInline(selectedSource.url);

  return <Shell><main className="resources-page"><section className="resources-hero"><p className="eyebrow"><span className="lime-dot" /> BLACKVAULT / RESOURCE GRAPH</p><h1>Don’t just take<br /><em>the course.</em></h1><p>Source material is indexed with context, embedded when publishers allow it, and connected to an evidence-based practice route.</p><div className="resource-stats"><div><strong>{pdfCatalog.length}+</strong><span>INDEXED PDF NODES</span></div><div><strong>{resourceCatalog.length}</strong><span>VERIFIED SOURCE NODES</span></div><div><strong>01</strong><span>EMBEDDED STUDY SHELF</span></div></div></section>
    <section className="resource-index"><div className="resource-index-top"><div><div className="section-index">01 <span>/</span> PDF READING ROOM</div><p className="resource-index-intro">Open the source, keep your place, and continue at the original institution whenever you are ready.</p></div><div className="resource-tools"><label><Search size={15} /><input aria-label="Search PDFs" placeholder="Search title, topic, author..." value={query} onChange={(event) => setQuery(event.target.value)} /></label><span><Filter size={14} /> {visible.length} MATCHES</span></div></div><div className="resource-filters">{filters.map((item) => <button className={filter === item ? "active" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="resource-list-grid pdf-grid">{visible.map((item, index) => <article className="resource-card pdf-card" key={item.id}><div className="resource-card-top"><span>{String(index + 1).padStart(3, "0")}</span><b><FileText size={12} /> PDF / {item.level}</b><span>{item.pages}</span></div><h2>{item.title}</h2><p>{item.note}</p><div className="pdf-meta"><span>{item.author}</span><span>{item.institution}</span></div><div className="resource-card-foot"><span>{item.topic} · {item.readTime}</span><Link className="reader-link" href={`/resources/read/${item.id}`}>OPEN READER <ArrowUpRight size={15} /></Link></div></article>)}</div>{visible.length === 0 && <div className="resource-empty"><Sparkles size={21} /><h2>No source node found.</h2><p>Try a broader topic, institution, or tag.</p></div>}</section>
    <section className="resource-inline-section"><div className="resource-inline-section__head"><div><div className="section-index">02 <span>/</span> PRIMARY SOURCE SHELF</div><h2>Read the source<br /><i>in context.</i></h2><p>These verified documentation and course pages open in Rampage when the publisher supports an embedded reader. The original remains one click away.</p></div><span><MonitorUp size={15} /> {canEmbed ? "INLINE SOURCE READY" : "PUBLISHER LINK"}</span></div><div className="resource-inline-layout"><div className="resource-inline-list" role="list">{resourceCatalog.map((resource) => <button type="button" role="listitem" className={resource.label === selectedSource.label && resource.url === selectedSource.url ? "is-active" : ""} onClick={() => setSelectedSource(resource)} key={`${resource.label}-${resource.url}`}><span><ResourceBadge resource={resource} />{resource.source}</span><strong>{resource.label}</strong><small>{resource.note || "Verified primary source"}</small></button>)}</div><div className="resource-inline-reader"><div className="resource-inline-reader__bar"><span><ResourceBadge resource={selectedSource} /> {sourceHost(selectedSource.url)}</span><a href={selectedSource.url} target="_blank" rel="noreferrer">Open original <ExternalLink size={13} /></a></div>{canEmbed ? <iframe title={`Embedded source: ${selectedSource.label}`} src={sourceKind === "pdf" ? `${selectedSource.url}${selectedSource.url.includes("#") ? "" : "#view=FitH"}` : selectedSource.url} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" /> : <div className="resource-inline-reader__fallback"><Link2 size={22} /><h3>Open from the original publisher.</h3><p>This source has a restrictive embed policy. Its context remains in Rampage; the publisher controls the reading surface.</p><a href={selectedSource.url} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={14} /></a></div>}</div></div></section>
    <section className="resource-principles"><div><div className="section-index">03 <span>/</span> HOW WE CURATE</div><h2>Context before<br /><i>collection.</i></h2></div><div className="principle-grid"><p><BookOpen size={18} /><strong>ORIGINAL FIRST</strong>Every item points to the institution, author, repository, or project that owns the material.</p><p><Github size={18} /><strong>BUILDABLE</strong>Every practice route is bounded, safe, and connected to the source that explains it.</p></div></section></main></Shell>;
}
