export type AssessmentQuestion = { id: string; prompt: string; options: string[]; answer: number; explanation: string };

export const chapterQuizBank: Record<string, AssessmentQuestion[]> = {
  "networking-systems": [
    { id: "net-q1", prompt: "What is the main purpose of layering in a network architecture?", options: ["To separate responsibilities behind stable interfaces", "To eliminate all latency", "To replace IP addresses", "To make every device identical"], answer: 0, explanation: "Layering keeps responsibilities and interfaces separate so a change in one part does not require rewriting every other part." },
    { id: "net-q2", prompt: "What does a router primarily use to make a forwarding decision?", options: ["A destination network prefix", "A browser cookie", "A CPU instruction", "A PDF bookmark"], answer: 0, explanation: "Routers compare the destination address with routing prefixes to choose the next hop." },
    { id: "net-q3", prompt: "What problem does TCP congestion control respond to?", options: ["Too much traffic competing for network capacity", "A missing HTML tag", "A broken keyboard", "A compiler syntax error"], answer: 0, explanation: "Congestion control adapts sending behavior when traffic competes for limited capacity and queues grow." },
  ],
  "systems-fundamentals": [
    { id: "sf-q1", prompt: "Which abstraction lets a process use addresses without directly naming physical RAM?", options: ["Virtual memory", "Git", "TCP", "A shell alias"], answer: 0, explanation: "Virtual memory maps process-visible addresses to physical memory." },
    { id: "sf-q2", prompt: "What does a system call cross?", options: ["The user/kernel boundary", "A DNS zone", "A compiler phase", "A CSS module"], answer: 0, explanation: "System calls are the controlled interface from user programs into the kernel." },
    { id: "sf-q3", prompt: "What problem does Raft primarily address?", options: ["Consensus among replicas", "Rendering pixels", "Compressing PDFs", "Parsing HTML"], answer: 0, explanation: "Raft is a consensus algorithm for replicated state machines." },
  ],
  "ai-systems": [
    { id: "ai-q1", prompt: "What is the most useful first boundary when explaining an AI product?", options: ["Data, model, evaluation, serving, and user goal", "Only the model size", "Only the prompt", "Only the GPU brand"], answer: 0, explanation: "A system view separates the model from the surrounding data, evaluation, serving, and goal." },
    { id: "ai-q2", prompt: "Why does sequence length affect inference cost?", options: ["More tokens create more memory and compute work", "It changes the keyboard layout", "It disables batching", "It removes evaluation"], answer: 0, explanation: "Longer sequences increase attention, memory, and generation work." },
    { id: "ai-q3", prompt: "What should be versioned before claiming an AI change improved quality?", options: ["An evaluation set and its results", "Only a screenshot", "Only a model name", "A random prompt"], answer: 0, explanation: "A versioned evaluation set makes comparisons reproducible." },
  ],
  "ai-product-systems": [
    { id: "aps-q1", prompt: "What should be defined before choosing a model for an AI product?", options: ["The user, task, constraint, and measurable outcome", "The largest available context window", "A brand palette", "A deployment region only"], answer: 0, explanation: "A useful AI product starts with a concrete user problem and a measurable outcome; model choice follows that boundary." },
    { id: "aps-q2", prompt: "What is the purpose of a retrieval evaluation?", options: ["To check whether selected context supports the answer and its evidence", "To make every answer longer", "To remove the need for source material", "To guarantee zero latency"], answer: 0, explanation: "Retrieval must be judged by whether it provides relevant, traceable context for the task." },
    { id: "aps-q3", prompt: "Which operating signal belongs in an AI product brief?", options: ["Latency, cost, failures, quality, and user impact", "Only the prompt text", "Only the model's parameter count", "Only a screenshot"], answer: 0, explanation: "A product brief should make the feature's behavior and operating envelope inspectable." },
  ],
  "ai-evaluation-engineering": [
    { id: "aee-q1", prompt: "What makes an evaluation metric useful?", options: ["It supports a decision about the intended task", "It is large and impressive", "It changes on every run", "It ignores difficult cases"], answer: 0, explanation: "A metric earns its place when it helps decide whether the system meets a stated quality goal." },
    { id: "aee-q2", prompt: "Why include ambiguous and harmful cases in an evaluation set?", options: ["They expose failure modes hidden by easy examples", "They make the score look higher", "They replace human review", "They remove the need for versioning"], answer: 0, explanation: "Representative evaluation includes the cases where the system may be unsafe, uncertain, or misleading." },
    { id: "aee-q3", prompt: "What should a regression harness compare?", options: ["A versioned system against a stable set and baseline", "Only the newest prompt", "Only one successful example", "A random sample with no record"], answer: 0, explanation: "Repeatable comparisons need a stable evaluation set, a known baseline, and versioned results." },
  ],
  "ai-data-infrastructure": [
    { id: "adi-q1", prompt: "Why write a data contract before scaling a pipeline?", options: ["To state provenance, ownership, quality expectations, and allowed use", "To avoid inspecting source data", "To guarantee perfect retrieval", "To replace monitoring"], answer: 0, explanation: "A data contract makes assumptions about source, ownership, quality, and use explicit." },
    { id: "adi-q2", prompt: "What is a key risk when choosing chunk boundaries?", options: ["Splitting context so the evidence needed for an answer is lost", "Making every document identical", "Removing all metadata automatically", "Eliminating the need for embeddings"], answer: 0, explanation: "Chunking changes which relationships and evidence survive into the model context." },
    { id: "adi-q3", prompt: "What does retrieval freshness require?", options: ["Defined invalidation, ownership, and a way to detect stale context", "A larger model only", "No source timestamps", "A fixed prompt forever"], answer: 0, explanation: "Freshness is an operational promise that needs ownership and observable invalidation behavior." },
  ],
  "systems-research-lab": [
    { id: "sr-q1", prompt: "What makes a systems experiment useful?", options: ["A falsifiable question and observable evidence", "A larger font", "A longer README only", "An unrecorded intuition"], answer: 0, explanation: "Systems claims need questions, measurements, and reproducible evidence." },
    { id: "sr-q2", prompt: "What should a failure matrix include?", options: ["Failure modes, expected behavior, and observed evidence", "Only successful runs", "Only latency", "Only source code"], answer: 0, explanation: "A failure matrix connects failure scenarios to expected and measured behavior." },
    { id: "sr-q3", prompt: "Why trace a syscall boundary?", options: ["To connect user intent to kernel work", "To change DNS", "To style a dashboard", "To hide a failure"], answer: 0, explanation: "Tracing reveals the path from a user operation into the kernel." },
  ],
  "compiler-runtime-architecture": [
    { id: "cr-q1", prompt: "Why use an intermediate representation?", options: ["To separate program meaning from a particular machine or source syntax", "To avoid parsing", "To remove tests", "To replace the runtime"], answer: 0, explanation: "IR creates a stable boundary for analysis, optimization, and code generation." },
    { id: "cr-q2", prompt: "What does a calling convention specify?", options: ["How calls use registers, stack frames, and return values", "How PDFs are indexed", "How packets route", "How CSS is themed"], answer: 0, explanation: "Calling conventions define the ABI contract between compiled functions." },
    { id: "cr-q3", prompt: "What makes a benchmark credible?", options: ["A repeatable workload and a baseline", "One fast run", "A subjective claim", "No measurement"], answer: 0, explanation: "Benchmarks need repeatable inputs and a comparison point." },
  ],
  "cpp-engineering": [
    { id: "cpp-q1", prompt: "What does RAII make explicit?", options: ["Resource ownership and cleanup tied to object lifetime", "The CPU brand", "The network route", "The HTML structure"], answer: 0, explanation: "RAII ties cleanup to scope and object lifetime, reducing manual ownership mistakes." },
    { id: "cpp-q2", prompt: "Why choose a standard container by its complexity guarantee?", options: ["The access pattern and cost shape the design", "It guarantees every program is faster", "It removes the need for tests", "It makes ownership irrelevant"], answer: 0, explanation: "Container choice affects operations, complexity, invalidation, and the resulting behavior of the program." },
    { id: "cpp-q3", prompt: "What do concepts add to a template interface?", options: ["Visible requirements on the types that may be used", "Automatic memory safety for every program", "A replacement for the linker", "A guarantee that all algorithms are optimal"], answer: 0, explanation: "Concepts state constraints at the interface and improve diagnostics and overload selection." },
    { id: "cpp-q4", prompt: "What is the strongest first step when diagnosing a C++ performance issue?", options: ["Define a workload, collect a baseline, and measure", "Rewrite the whole program", "Add threads immediately", "Trust a visual guess"], answer: 0, explanation: "A repeatable workload and baseline turn an intuition into an inspectable performance claim." },
    { id: "cpp-q5", prompt: "What should a reproducible CMake project make clear?", options: ["Targets, dependencies, compile features, and build steps", "Only the executable name", "Only the developer's machine", "Only the source file count"], answer: 0, explanation: "A target-oriented build describes how the project is assembled and reproduced on another machine." },
    { id: "cpp-q6", prompt: "What belongs in a concurrency design before adding threads?", options: ["Ownership, synchronization, shutdown, and observable invariants", "Only a larger thread count", "Only a mutex around everything", "Only a benchmark screenshot"], answer: 0, explanation: "Concurrency is a coordination contract; the shared state, lifecycle, and evidence need to be explicit." },
  ],
  "c-foundations": [
    { id: "c-q1", prompt: "What does a compiler do with a C source file?", options: ["Translates human-readable source into a form the machine can execute", "Stores the program in a PDF", "Routes network packets", "Creates a database table"], answer: 0, explanation: "A compiler translates source code into object code or an executable through the toolchain." },
    { id: "c-q2", prompt: "Why does a C string need a terminator?", options: ["Functions need a boundary to know where the character sequence ends", "It makes every string immutable", "It allocates heap memory automatically", "It prevents all input errors"], answer: 0, explanation: "Traditional C strings use a null character to mark the end of the character sequence." },
    { id: "c-q3", prompt: "What does dereferencing a pointer mean?", options: ["Accessing the object stored at the pointer's address", "Converting C into C++", "Freeing memory automatically", "Starting a new process"], answer: 0, explanation: "The dereference operator accesses the object designated by a valid pointer." },
    { id: "c-q4", prompt: "What is the owner of dynamically allocated memory responsible for?", options: ["Tracking its lifetime and releasing it exactly once", "Making the memory global", "Ignoring allocation failure", "Changing the compiler standard"], answer: 0, explanation: "Explicit ownership means a program must define success, failure, and cleanup paths." },
    { id: "c-q5", prompt: "What makes a C input boundary safer?", options: ["A defined maximum length, checked conversion, and explicit failure behavior", "Reading until memory happens to stop", "Ignoring return values", "Using a larger global buffer"], answer: 0, explanation: "Safe input handling controls length and conversion and makes rejected input visible." },
    { id: "c-q6", prompt: "What should a beginner include in a finished C project?", options: ["A reproducible build, tests or sample runs, explanation, and known limitations", "Only a screenshot", "Every possible C feature", "No error handling"], answer: 0, explanation: "A small, explainable artifact with evidence and limits is stronger than an unreviewed feature pile." },
  ],
};

export const finalAssessmentBank: Record<string, AssessmentQuestion[]> = {
  "cpp-engineering": [
    { id: "cpp-f1", prompt: "Which design best communicates ownership in a modern C++ program?", options: ["A type whose lifetime and cleanup follow scope, with ownership visible at the boundary", "Raw pointers everywhere with comments", "A global cleanup function called at exit", "A larger class hierarchy"], answer: 0, explanation: "Ownership should be visible in types and interfaces so lifetime is inspectable and testable." },
    { id: "cpp-f2", prompt: "What is a useful role for the C++ standard library?", options: ["Use well-specified containers and algorithms before rebuilding them", "Avoid learning complexity guarantees", "Replace all design decisions", "Guarantee no bugs"], answer: 0, explanation: "The library provides tested vocabulary, but engineers still choose by contract, complexity, and fit." },
    { id: "cpp-f3", prompt: "What makes a C++ test suite useful?", options: ["It states behavior across normal, boundary, and failure cases", "It only maximizes line coverage", "It records one successful run", "It hides implementation failures"], answer: 0, explanation: "Tests are evidence of behavior and should protect the contract, including important failure paths." },
    { id: "cpp-f4", prompt: "What should a performance claim include?", options: ["A repeatable workload, baseline, measurement method, result, and limits", "Only a faster-looking implementation", "Only a profiler image", "Only the compiler version"], answer: 0, explanation: "Performance evidence needs context so another engineer can reproduce and challenge the conclusion." },
    { id: "cpp-f5", prompt: "What is the capstone handoff meant to prove?", options: ["The tool can be built, tested, explained, and improved with known limits", "The code has no possible bugs", "The program uses every C++ feature", "The largest possible binary was produced"], answer: 0, explanation: "The handoff makes the artifact, evidence, trade-offs, and limitations legible to another engineer." },
  ],
  "c-foundations": [
    { id: "c-f1", prompt: "Which C project is most ready to share?", options: ["One with a reproducible build, tests or sample runs, clear scope, and known limitations", "One that only works on the author's machine", "One with no failure handling", "One that hides its source"], answer: 0, explanation: "A useful handoff lets another person build, inspect, and challenge the program." },
    { id: "c-f2", prompt: "What is a strong way to review pointer code?", options: ["State valid objects, ownership, lifetime, and cleanup for every pointer", "Assume every non-null pointer is safe", "Remove all checks", "Use comments instead of tests"], answer: 0, explanation: "Pointer safety depends on validity, lifetime, ownership, and the paths that release resources." },
    { id: "c-f3", prompt: "Why should C programs compile with warnings enabled?", options: ["Warnings expose suspicious code before it becomes a runtime failure", "Warnings replace testing", "Warnings make memory safe automatically", "Warnings remove the need for design"], answer: 0, explanation: "Compiler diagnostics are an early feedback channel, but they complement tests and review." },
    { id: "c-f4", prompt: "What does secure C practice emphasize?", options: ["Explicit bounds, checked conversions, validated input, and defined failure behavior", "Bigger buffers without limits", "Ignoring return values", "Trusting all external input"], answer: 0, explanation: "Secure C makes boundaries and failure behavior explicit rather than relying on optimistic assumptions." },
    { id: "c-f5", prompt: "What should the C capstone demonstrate?", options: ["A small system whose behavior, build, tests, and limits can be explained", "Every feature in the language", "A benchmark without a workload", "A program with no documentation"], answer: 0, explanation: "The capstone is evidence of disciplined construction, not a claim that the program has no possible bugs." },
  ],
  "ai-product-systems": [
    { id: "aps-f1", prompt: "What is the strongest first step for an AI feature?", options: ["Define the user problem, task, constraints, and quality bar", "Choose the biggest model", "Skip evaluation until launch", "Start with a dashboard"], answer: 0, explanation: "A bounded user problem and quality bar make later architecture and evaluation decisions testable." },
    { id: "aps-f2", prompt: "What should retrieval evidence let a reviewer do?", options: ["Trace an answer back to relevant source context", "Confirm that every answer is correct automatically", "Avoid reading source material", "Hide low-confidence results"], answer: 0, explanation: "Retrieval should improve inspectability and evidence, not create an unreviewable black box." },
    { id: "aps-f3", prompt: "Why version evaluation results?", options: ["To compare changes against a known set and baseline", "To make scores impossible to challenge", "To remove product judgment", "To avoid monitoring"], answer: 0, explanation: "Versioning preserves the comparison needed to understand whether a change actually helped." },
    { id: "aps-f4", prompt: "Which set of signals best describes operating an AI feature?", options: ["Quality, latency, cost, failures, and user impact", "Only token count", "Only uptime", "Only a model card"], answer: 0, explanation: "A production feature has technical and user-facing behavior that must be observed together." },
    { id: "aps-f5", prompt: "What belongs in a responsible AI system brief?", options: ["Data, model, evaluation, costs, failure modes, and next experiment", "Only a prompt", "Only a vendor name", "Only a launch date"], answer: 0, explanation: "The brief should make the system's evidence and limits legible to the next person." },
  ],
  "ai-evaluation-engineering": [
    { id: "aee-f1", prompt: "What is an evaluation contract?", options: ["A defined task, dataset, rubric, metric, and decision rule", "A model purchase order", "A prompt library without outcomes", "A dashboard theme"], answer: 0, explanation: "An evaluation contract states what is measured, how it is judged, and what decision follows." },
    { id: "aee-f2", prompt: "What makes a test set representative?", options: ["It covers normal, difficult, ambiguous, and risk-relevant cases", "It contains only easy examples", "It changes silently each run", "It excludes real failure modes"], answer: 0, explanation: "A useful set reflects the range of behavior the system will meet in practice." },
    { id: "aee-f3", prompt: "What does a rubric add beyond a raw score?", options: ["An explanation of why an output succeeds or fails", "A guarantee of truth", "A replacement for examples", "A way to remove human judgment"], answer: 0, explanation: "Rubrics make quality judgments more consistent and more useful for debugging." },
    { id: "aee-f4", prompt: "Why track evaluation drift?", options: ["Because data, users, and system behavior change over time", "Because scores never need context", "Because monitoring replaces testing", "Because old results are always wrong"], answer: 0, explanation: "A stable score can become misleading when the task or operating distribution changes." },
    { id: "aee-f5", prompt: "What makes an evaluation report reproducible?", options: ["Versioned data, procedure, environment, results, and stated limits", "Only a final number", "Only a chart", "Only a model name"], answer: 0, explanation: "Reproduction requires enough context to repeat and challenge the conclusion." },
  ],
  "ai-data-infrastructure": [
    { id: "adi-f1", prompt: "What should a data contract make explicit?", options: ["Source, ownership, provenance, quality, and permitted use", "Only file size", "Only embedding dimension", "Only a vendor"], answer: 0, explanation: "A contract turns hidden pipeline assumptions into inspectable responsibilities." },
    { id: "adi-f2", prompt: "Why is chunking a model-facing decision?", options: ["It determines which relationships and evidence reach the context window", "It only changes file names", "It removes retrieval", "It guarantees factuality"], answer: 0, explanation: "Chunk boundaries shape the context available to the model and therefore affect answer quality." },
    { id: "adi-f3", prompt: "What is the proper role of embeddings in retrieval?", options: ["Retrieve useful candidates that still require relevance and evidence checks", "Prove that a passage is true", "Replace source provenance", "Guarantee the best answer"], answer: 0, explanation: "Similarity helps find candidates; it is not the same as truth or task correctness." },
    { id: "adi-f4", prompt: "What does a freshness policy define?", options: ["When context is stale, who owns invalidation, and how it is observed", "A permanent cache with no expiry", "Only model temperature", "Only document color"], answer: 0, explanation: "Freshness is a measurable operational policy, not an assumption hidden in the pipeline." },
    { id: "adi-f5", prompt: "What should a retrieval runbook cover?", options: ["Empty, wrong, stale, and untraceable results with diagnostic steps", "Only successful queries", "Only database uptime", "Only prompt formatting"], answer: 0, explanation: "A runbook turns retrieval failure modes into repeatable operational actions." },
  ],
  "networking-systems": [
    { id: "net-f1", prompt: "Which sequence best describes a typical web request path?", options: ["Name resolution, transport connection, application request, response", "Compiler, kernel panic, PDF export, response", "Only DNS with no transport", "Only a switch lookup"], answer: 0, explanation: "A web request commonly resolves a name, establishes or reuses transport, sends an application request, and receives a response." },
    { id: "net-f2", prompt: "What is the role of a subnet prefix?", options: ["It identifies the network boundary used for local delivery and routing", "It encrypts every packet", "It assigns a process ID", "It replaces a port number"], answer: 0, explanation: "A prefix separates the network portion from the host portion and supports forwarding decisions." },
    { id: "net-f3", prompt: "What does TCP provide above IP?", options: ["Ordered, reliable byte-stream delivery with flow and congestion control", "A wireless radio signal", "A DNS zone", "A physical cable"], answer: 0, explanation: "TCP adds reliable ordered delivery and controls the sender based on receiver capacity and network congestion." },
    { id: "net-f4", prompt: "Which troubleshooting step is strongest?", options: ["Start from a concrete symptom, choose a measurement, and record the evidence", "Change several devices at once", "Trust a diagram without measuring", "Restart everything and record nothing"], answer: 0, explanation: "A defensible troubleshooting loop connects a symptom to a specific measurement and preserves the result for comparison." },
    { id: "net-f5", prompt: "What is a useful network security boundary?", options: ["A stated trust boundary with controls and expected failure behavior", "A larger logo", "An untested default password", "A hidden route"], answer: 0, explanation: "Security work is clearer when trust boundaries, controls, and failure behavior are explicit and testable." },
  ],
  "systems-fundamentals": [
    { id: "sf-f1", prompt: "Which boundary is protected by a system call?", options: ["User space and kernel space", "HTML and CSS", "DNS and HTTP", "Git and Vim"], answer: 0, explanation: "System calls cross the user/kernel boundary." },
    { id: "sf-f2", prompt: "What does virtual memory provide?", options: ["A process-visible address space mapped to physical memory", "A replacement for tests", "A network route", "A shell prompt"], answer: 0, explanation: "Virtual memory maps process addresses to physical storage." },
    { id: "sf-f3", prompt: "What does TCP add over an unreliable network?", options: ["Ordered, reliable byte-stream delivery", "A compiler", "A file system", "A CPU"], answer: 0, explanation: "TCP manages ordering, retransmission, flow, and congestion." },
    { id: "sf-f4", prompt: "What does a replicated state machine need?", options: ["A way for replicas to agree on an ordered log", "Only more RAM", "A CSS framework", "A PDF reader"], answer: 0, explanation: "Consensus orders commands consistently across replicas." },
    { id: "sf-f5", prompt: "What makes a project result defensible?", options: ["A reproducible procedure, evidence, and stated limits", "A confident claim", "A hidden test", "A larger UI"], answer: 0, explanation: "Defensible work explains how it was tested and where it may fail." },
  ],
  "ai-systems": [
    { id: "ai-f1", prompt: "Which component measures whether an AI system works for its intended use?", options: ["Evaluation", "Color palette", "Keyboard", "DNS"], answer: 0, explanation: "Evaluation compares behavior against an explicit goal." },
    { id: "ai-f2", prompt: "What does tokenization do?", options: ["Maps text into model-readable units", "Deploys a GPU", "Creates a database", "Runs a browser"], answer: 0, explanation: "Tokenization converts text into discrete units used by the model." },
    { id: "ai-f3", prompt: "Why monitor an AI service in production?", options: ["To observe latency, failures, cost, drift, and user impact", "To replace tests", "To hide errors", "To increase font size"], answer: 0, explanation: "Operational signals reveal whether the system remains useful and safe." },
    { id: "ai-f4", prompt: "What is a good first AI architecture decision?", options: ["Choose the smallest components that satisfy the goal and quality bar", "Choose the largest model by default", "Skip evaluation", "Avoid logging"], answer: 0, explanation: "Simple systems are easier to measure, operate, and improve." },
    { id: "ai-f5", prompt: "What should an AI system brief include?", options: ["Data, model, tests, costs, failure modes, and next experiment", "Only a prompt", "Only a screenshot", "Only a vendor name"], answer: 0, explanation: "A useful brief makes the system and its limits inspectable." },
  ],
  "systems-research-lab": [
    { id: "sr-f1", prompt: "What is the core unit of systems research?", options: ["A falsifiable question with evidence", "A slogan", "A screenshot", "An unmeasured intuition"], answer: 0, explanation: "Research needs a question and evidence that could change the conclusion." },
    { id: "sr-f2", prompt: "What should a trace help you do?", options: ["Answer a concrete operational question", "Collect noise forever", "Replace a test", "Hide a timing issue"], answer: 0, explanation: "Useful traces are designed around a question." },
    { id: "sr-f3", prompt: "What does replication require you to state?", options: ["A consistency promise and failure behavior", "Only the server brand", "Only the UI", "Only the happy path"], answer: 0, explanation: "Replication is a behavioral promise under failure." },
    { id: "sr-f4", prompt: "Why test restarts and partitions?", options: ["They expose behavior outside the happy path", "They improve typography", "They remove the need for logs", "They guarantee availability"], answer: 0, explanation: "Failure tests reveal whether the design matches its claims." },
    { id: "sr-f5", prompt: "What makes a systems report reproducible?", options: ["Procedure, environment, measurements, and limits", "Only conclusions", "Only code", "Only citations"], answer: 0, explanation: "Readers need enough context to repeat and assess the work." },
  ],
  "compiler-runtime-architecture": [
    { id: "cr-f1", prompt: "What does a parser produce?", options: ["A structured representation of program syntax", "A network packet", "A database row", "A certificate"], answer: 0, explanation: "Parsers turn tokens into structured syntax." },
    { id: "cr-f2", prompt: "Why compile through an IR?", options: ["It creates a stable boundary for analysis and optimization", "It removes the runtime", "It skips tests", "It replaces the lexer"], answer: 0, explanation: "IR decouples source meaning from target execution details." },
    { id: "cr-f3", prompt: "What does a runtime manage?", options: ["Execution concerns such as calls, memory, and object layout", "Only source formatting", "Only network routes", "Only documentation"], answer: 0, explanation: "A runtime implements the execution model behind language features." },
    { id: "cr-f4", prompt: "What should happen before optimizing?", options: ["Measure a reproducible baseline", "Guess", "Delete tests", "Hide the benchmark"], answer: 0, explanation: "Measurement prevents optimizing the wrong bottleneck." },
    { id: "cr-f5", prompt: "What is a calling convention?", options: ["An ABI contract for function calls", "A PDF standard", "A UI pattern", "A network protocol"], answer: 0, explanation: "It defines how compiled functions exchange arguments and results." },
  ],
};
